version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=wheel
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8080:80'
    depends_on:
      - db

volumes:
  db-data:
